# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cab802e035336b20d72b90489c958d9d2bbd1af71fe755522f7a2d4e99af5eb41cf860db726e5d13db0dfce660cd047d59553bbfd24f416aa08a2e9bc03a9fc

test:
  secret_key_base: 8256905a7c2d8a5339723042f7ae86cdbba3d8e3a0f9fb7dbf57ee2e5fbdf0d169fd0d39f9289b58c062d093a41908ce465b5c2a9b900667573945a5053aafa8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
