# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8f884288c7cba807c0b98b95abb2f7a2cf220c39902565ef01502d31ae1cf4bcb987214948b92a9852eb892644e7a959b3ce1804d6d59ba3de132bcd4a14f19

test:
  secret_key_base: 208f46fa69035227a7cb8065449eadc5f6ca64efd671ca59a9cc980e143b847e967bbacd6c51562b5123ad1a4cc43d0d900e78bd9f2ba4cd71869bff20eea9e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
